SportsPlanning\PlanningConfiguration:
  exclusion_policy: ALL
  exclude: false
  properties:
    pouleStructure:
      type: SportsHelpers\PouleStructure
    sportVariantsWithFields:
      type: array<SportsPlanning\Sports\SportWithNrOfFieldsAndNrOfCycles>
    refereeInfo:
      type: SportsPlanning\Referee\PlanningRefereeInfo
    perPoule:
      type: boolean