name: Coverage

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: xdebug
          tools: phpunit
          coverage: xdebug

      - uses: php-actions/composer@v6
        with:
          php_version: "8.3"

      - name: PHPUnit Coverage
        uses: php-actions/phpunit@v4
        with:
          php_version: 8.3
          php_extensions: xdebug
          configuration: tests/phpunit.xml
          args: --coverage-text
        env:
          XDEBUG_MODE: coverage
