name: Tests

on: [push, pull_request]

jobs:
  build-test-2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: xdebug

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v3

      - name: Static analysis
        run: vendor/bin/psalm

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v4
        env:
          XDEBUG_MODE: coverage
        with:
          #bootstrap: vendor/autoload.php
          configuration: tests/phpunit.xml
          php_extensions: xdebug
          args: tests --coverage-clover ./tests/coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          #token: ${{ secrets.CODE_COV_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./tests/coverage.xml
          verbose: true